import { AdminLayout } from "@/components/layout/admin-layout";
import { CustomerLayout } from "@/components/layout/customer-layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useGetRefundByRef } from "@workspace/api-client-react";
import { Link, useParams } from "wouter";
import { ArrowLeft, Download, RefreshCw, ReceiptText } from "lucide-react";

const STATUS_COLORS: Record<string, string> = {
  pending: "bg-yellow-100 text-yellow-800",
  approved: "bg-green-100 text-green-800",
  rejected: "bg-red-100 text-red-800",
  processed: "bg-blue-100 text-blue-800",
};

const STATUS_LABELS: Record<string, string> = {
  pending: "Pending Review",
  approved: "Approved",
  rejected: "Rejected",
  processed: "Refunded",
};

interface Props {
  params: { ref: string };
}

export default function RefundDetail({ params }: Props) {
  const ref = params.ref;
  const { data: refund, isLoading } = useGetRefundByRef(ref, {
    query: { enabled: !!ref } as any,
  });

  function downloadReceipt() {
    if (!refund) return;
    const lines = [
      "EASY AGRA — REFUND RECEIPT",
      "═══════════════════════════",
      `Refund Ref : ${refund.refundRef}`,
      `Status     : ${STATUS_LABELS[refund.status] ?? refund.status}`,
      `Amount     : ₹${Number(refund.amount).toLocaleString("en-IN")}`,
      `Reason     : ${refund.reason}`,
      `Requested  : ${new Date(refund.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
      refund.processedAt
        ? `Processed  : ${new Date(refund.processedAt).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`
        : "",
      refund.payment?.bookingRef
        ? `Booking Ref: ${refund.payment.bookingRef}`
        : "",
      "",
      "Generated by Easy Agra Platform",
    ]
      .filter(Boolean)
      .join("\n");

    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `refund-${refund.refundRef}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <CustomerLayout>
      <div className="max-w-xl mx-auto px-4 py-6 space-y-5">
        <div className="flex items-center gap-3">
          <Link href="/refunds">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <h1 className="text-lg font-bold text-foreground">Refund Detail</h1>
        </div>

        {isLoading && (
          <div className="text-center py-12 text-muted-foreground">
            <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2" />
            Loading…
          </div>
        )}

        {!isLoading && !refund && (
          <div className="text-center py-12">
            <ReceiptText className="w-10 h-10 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">Refund not found</p>
          </div>
        )}

        {refund && (
          <>
            <Card className="border border-border/60">
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="font-mono text-base">
                    {refund.refundRef}
                  </CardTitle>
                  <Badge
                    className={
                      STATUS_COLORS[refund.status] ?? "bg-gray-100 text-gray-700"
                    }
                  >
                    {STATUS_LABELS[refund.status] ?? refund.status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-3">
                <Row
                  label="Refund Amount"
                  value={`₹${Number(refund.amount).toLocaleString("en-IN")}`}
                  highlight
                />
                <Row label="Reason" value={refund.reason} />
                {(refund as any).payment?.bookingRef && (
                  <Row
                    label="Booking Ref"
                    value={(refund as any).payment.bookingRef}
                    mono
                  />
                )}
                {(refund as any).payment?.bookingType && (
                  <Row
                    label="Booking Type"
                    value={(refund as any).payment.bookingType}
                  />
                )}
                <Row
                  label="Requested On"
                  value={new Date(refund.createdAt).toLocaleDateString("en-IN", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                  })}
                />
                {refund.processedAt && (
                  <Row
                    label="Processed On"
                    value={new Date(refund.processedAt).toLocaleDateString(
                      "en-IN",
                      {
                        day: "numeric",
                        month: "long",
                        year: "numeric",
                      },
                    )}
                  />
                )}
                {(refund as any).processedByName && (
                  <Row
                    label="Processed By"
                    value={(refund as any).processedByName}
                  />
                )}
                {refund.rejectionReason && (
                  <div className="bg-red-50 rounded-md p-3">
                    <p className="text-xs font-medium text-red-700">
                      Rejection Reason
                    </p>
                    <p className="text-sm text-red-800 mt-0.5">
                      {refund.rejectionReason}
                    </p>
                  </div>
                )}
                {refund.notes && (
                  <div className="bg-muted/50 rounded-md p-3">
                    <p className="text-xs font-medium text-muted-foreground">
                      Admin Note
                    </p>
                    <p className="text-sm mt-0.5">{refund.notes}</p>
                  </div>
                )}
              </CardContent>
            </Card>

            {(refund.status === "approved" || refund.status === "processed") && (
              <Button
                variant="outline"
                className="w-full"
                onClick={downloadReceipt}
              >
                <Download className="w-4 h-4 mr-2" />
                Download Receipt
              </Button>
            )}
          </>
        )}
      </div>
    </CustomerLayout>
  );
}

function Row({
  label,
  value,
  highlight,
  mono,
}: {
  label: string;
  value: string;
  highlight?: boolean;
  mono?: boolean;
}) {
  return (
    <div className="flex justify-between gap-2 text-sm">
      <span className="text-muted-foreground shrink-0">{label}</span>
      <span
        className={`text-right ${highlight ? "font-bold text-primary text-base" : mono ? "font-mono" : "font-medium"}`}
      >
        {value}
      </span>
    </div>
  );
}
