import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import ownerRequestsRouter from "./owner-requests";
import hotelsRouter from "./hotels";
import roomsRouter from "./rooms";
import bookingsRouter from "./bookings";
import reviewsRouter from "./reviews";
import restaurantsRouter from "./restaurants";
import reservationsRouter from "./reservations";
import spasRouter from "./spas";
import spaServicesRouter from "./spa-services";
import spaAppointmentsRouter from "./spa-appointments";
import touristPlacesRouter from "./tourist-places";
import paymentsRouter from "./payments";
import refundsRouter from "./refunds";
import cancellationsRouter from "./cancellations";
import commissionsRouter from "./commissions";
import hotelCommissionAgreementsRouter from "./hotel-commission-agreements";
import earningsRouter from "./earnings";
import payoutsRouter from "./payouts";
import reportsRouter from "./reports";
import tripsRouter from "./trips";
import tripRecommendationsRouter from "./trip-recommendations";
import supportTicketsRouter from "./support-tickets";
import notificationsRouter from "./notifications";
import activityLogsRouter from "./activity-logs";
import platformSettingsRouter from "./platform-settings";
import dashboardRouter from "./dashboard";
import couponsRouter from "./coupons";
import securityRouter from "./security";
import pushNotificationsRouter from "./push-notifications";
import marketingRouter from "./marketing";
import googleAuthRouter from "./google-auth";
import transportRouter from "./transport";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(googleAuthRouter);
router.use(usersRouter);
router.use(ownerRequestsRouter);
router.use(hotelsRouter);
router.use(roomsRouter);
router.use(bookingsRouter);
router.use(reviewsRouter);
router.use(restaurantsRouter);
router.use(reservationsRouter);
router.use(spasRouter);
router.use(spaServicesRouter);
router.use(spaAppointmentsRouter);
router.use(touristPlacesRouter);
router.use(paymentsRouter);
router.use(refundsRouter);
router.use(cancellationsRouter);
router.use(commissionsRouter);
router.use(hotelCommissionAgreementsRouter);
router.use(earningsRouter);
router.use(payoutsRouter);
router.use(reportsRouter);
router.use(tripsRouter);
router.use(tripRecommendationsRouter);
router.use(supportTicketsRouter);
router.use(notificationsRouter);
router.use(activityLogsRouter);
router.use(platformSettingsRouter);
router.use(couponsRouter);
router.use(securityRouter);
router.use(pushNotificationsRouter);
router.use(marketingRouter);
router.use(transportRouter);
router.use(dashboardRouter);

export default router;
